# Calibrating the Liquid Drop Model

The purpose of this challenge is for you to calibrate the Liquid Drop Model https://en.wikipedia.org/wiki/Semi-empirical_mass_formula and compare the results of a "black box" calibration vs a principled Bayesian one.

Your task is to:

- Import the data from the AME 2016 table (included in the github). We are only using nuclei above A=16 to avoid light nuclei where the LDM fails particularly. Perform a curve fit using the built in functions from python (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) and take note of the reported uncertainties in the parameters. 
- Make a plot of the residuals and estimate the model error on its best fit. 
- Make a model calibration using the Bayesian formalism we defined and a Metropolis sampler. For the error, use your estimation from the previous point (the model error in this case is much smaller than the actual experimental uncertainties). 
- Plot the corner plot posterior as well as the model values on the Binding Energy per nucleon for the Calcium chain up to 60Ca including the available experimental data.
- What would be the results if you have used in the calibration the Binding Energy per nucleon instead of the total Binding Energy?
- Bonus: Find the experimental error in the masses and repeat the calibration using only experimental errors. This should give a good demonstration on the dangers of not taking into account model errors. 


In [70]:
import numpy as np
import scipy
import matplotlib.pyplot as plt

TypeError: 'list' object is not callable

In [54]:
data = np.loadtxt('Masses2016.txt', skiprows=1)

def LDM(x,*params):
    #x = (n,z)
    #params= parameters (volume, surface, asymmetry, Coulomb)
    
    n=x[0]
    z=x[1]
    
    #return a*(n+z) - b*(n+z)**(2/3) - c*((n-z)**2/(n+z)) - d*((z**2)/((n+z)**(1/3)))
    return params[0]*(n+z) - params[1]*(n+z)**(2/3) - params[2]*((n-z)**2/(n+z)) - params[3]*((z**2)/((n+z)**(1/3)))

In [60]:
xdata = data[:,:2].T
ydata = data[:,2]
p0=np.array=([1,1,1,1])
mean, cov = scipy.optimize.curve_fit(LDM,xdata,ydata,p0=p0)
print(mean)
print(cov)

[10.4618677  14.24325763  5.40685517  0.49088531]
[[1.81140977e-03 5.57812446e-03 4.07639863e-03 1.24611243e-04]
 [5.57812446e-03 1.74525926e-02 1.23581620e-02 3.76099757e-04]
 [4.07639863e-03 1.23581620e-02 1.12402635e-02 2.74655197e-04]
 [1.24611243e-04 3.76099757e-04 2.74655197e-04 8.86830024e-06]]


In [66]:
y_the = LDM(xdata,*mean)
resids = ydata - y_the


In [68]:
plt.scatter(data[:,0],data[:,1],resids)
plt.colorbar()

NameError: name 'plt' is not defined

In [69]:
!pip install matplotlib